import type { Exercise } from "./types";

/**
 * Bibliothèque calibrée sur l'équipement dispo : barre de tractions, haltères 10 kg max,
 * bandes 15/35 kg, handgrip, chaise, table. Priorité "primaire" = cible Toji
 * (épaules, dos, trapèzes, avant-bras, abdos/obliques, cou).
 *
 * `progression` liste les leviers encore disponibles une fois les 10 kg atteints :
 * c'est la contrainte structurante de tout ce programme.
 */
export const SEED_EXERCISES: Omit<Exercise, "id">[] = [
  // ---------------- PUSH ----------------
  {
    name: "Pompes archer",
    type: "musculation",
    zones: ["pecs", "epaules"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["push", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "6-8 / côté",
    progression: ["reps", "amplitude", "tempo", "lest"],
    instructions: "Bras tendu sur le côté, descente contrôlée sur le bras plié. Alterner.",
  },
  {
    name: "Pompes piquées (pike push-ups)",
    type: "musculation",
    zones: ["epaules", "trapezes"],
    priority: "primaire",
    equipment: ["poids du corps", "chaise"],
    splitDays: ["push", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "8-12",
    progression: ["reps", "levier", "tempo", "amplitude"],
    instructions:
      "Pieds surélevés sur la chaise, bassin haut. Le nez descend devant les mains. Surélever davantage les pieds pour durcir.",
  },
  {
    name: "Développé militaire haltères",
    type: "musculation",
    zones: ["epaules"],
    priority: "primaire",
    equipment: ["haltères"],
    splitDays: ["push"],
    defaultSets: 4,
    defaultReps: "10-14",
    progression: ["charge", "reps", "tempo", "unilateral", "densite"],
    instructions:
      "Debout, gainage serré. Tempo 2-0-2. Une fois 4×14 à 10 kg atteint, passer en unilatéral plutôt que d'ajouter des répétitions.",
  },
  {
    name: "Développé épaules bande (35 kg)",
    type: "musculation",
    zones: ["epaules"],
    priority: "primaire",
    equipment: ["bande 35kg"],
    splitDays: ["push"],
    defaultSets: 3,
    defaultReps: "12-15",
    progression: ["bande", "reps", "tempo", "unilateral"],
    instructions:
      "Bande sous les pieds. La tension max en haut compense le manque de charge libre. Écarter les pieds pour augmenter la tension.",
  },
  {
    name: "Élévations latérales",
    type: "musculation",
    zones: ["epaules"],
    priority: "primaire",
    equipment: ["haltères", "bandes"],
    splitDays: ["push", "pull"],
    defaultSets: 4,
    defaultReps: "15-20",
    progression: ["reps", "tempo", "densite", "bande"],
    instructions:
      "Clé de la largeur d'épaules. Léger, strict, sans balancier. Ici la charge n'a jamais besoin d'être lourde : privilégier le tempo et les séries longues.",
  },
  {
    name: "Élévations latérales penché (rear delt)",
    type: "musculation",
    zones: ["epaules", "dos"],
    priority: "primaire",
    equipment: ["haltères", "bandes"],
    splitDays: ["push", "pull"],
    defaultSets: 4,
    defaultReps: "15-20",
    progression: ["reps", "tempo", "densite", "bande"],
    instructions: "Buste à 45°, deltoïde postérieur. Négligé et essentiel pour le V.",
  },
  {
    name: "Dips entre deux chaises",
    type: "musculation",
    zones: ["pecs", "bras"],
    priority: "secondaire",
    equipment: ["chaise"],
    splitDays: ["push"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "8-12",
    progression: ["reps", "lest", "tempo", "amplitude"],
    instructions: "Amplitude contrôlée, épaules basses.",
  },
  {
    name: "Pompes diamant",
    type: "musculation",
    zones: ["bras", "pecs"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["push"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "10-15",
    progression: ["reps", "levier", "tempo", "lest"],
    instructions: "Mains en losange, coudes le long du corps.",
  },
  {
    name: "Handstand hold contre mur",
    type: "musculation",
    zones: ["epaules", "abdos"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["push", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "20-45 s",
    progression: ["reps", "amplitude", "levier"],
    instructions: "Gainage vertical, épaules verrouillées. Progresser en durée puis en amplitude.",
  },

  // ---------------- PULL ----------------
  {
    name: "Tractions pronation",
    type: "musculation",
    zones: ["dos", "avant-bras"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["pull", "fullbody"],
    bodyweight: true,
    defaultSets: 5,
    defaultReps: "max",
    progression: ["reps", "lest", "tempo", "levier"],
    instructions: "Mouvement roi pour le V. Amplitude complète, pas de kipping.",
  },
  {
    name: "Tractions prise large",
    type: "musculation",
    zones: ["dos", "epaules"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["pull"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "5-8",
    progression: ["reps", "lest", "tempo"],
    instructions: "Cible les dorsaux en largeur. Tirer les coudes vers les hanches.",
  },
  {
    name: "Tractions supination (chin-ups)",
    type: "musculation",
    zones: ["dos", "bras"],
    priority: "secondaire",
    equipment: ["barre de tractions"],
    splitDays: ["pull"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "8-12",
    progression: ["reps", "lest", "tempo"],
    instructions:
      "Plus de biceps, utile pour charger le dos quand les pronations fatiguent.",
  },
  {
    name: "Tractions lestées",
    type: "musculation",
    zones: ["dos"],
    priority: "primaire",
    equipment: ["barre de tractions", "haltères", "sac à dos"],
    splitDays: ["pull"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "5-6",
    progression: ["lest", "reps", "tempo"],
    instructions:
      "Haltère entre les pieds ou sac chargé. Dès que 5×8 propres passent, ajouter du poids. C'est le principal exutoire de charge une fois les haltères plafonnés.",
  },
  {
    name: "Rowing haltères unilatéral",
    type: "musculation",
    zones: ["dos", "trapezes"],
    priority: "primaire",
    equipment: ["haltères", "chaise"],
    splitDays: ["pull"],
    defaultSets: 4,
    defaultReps: "12-15",
    progression: ["charge", "reps", "tempo", "densite"],
    instructions: "Appui main/genou sur la chaise. Tirer vers la hanche, pause 1 s en haut.",
  },
  {
    name: "Rowing bande (35 kg)",
    type: "musculation",
    zones: ["dos", "trapezes"],
    priority: "primaire",
    equipment: ["bande 35kg"],
    splitDays: ["pull"],
    defaultSets: 4,
    defaultReps: "15",
    progression: ["bande", "reps", "tempo", "unilateral"],
    instructions: "Ancrage bas ou pieds. Serrer les omoplates 1 s.",
  },
  {
    name: "Rowing australien sous la table",
    type: "musculation",
    zones: ["dos", "trapezes"],
    priority: "primaire",
    equipment: ["table"],
    splitDays: ["pull", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "10-15",
    progression: ["levier", "reps", "tempo", "lest"],
    instructions:
      "Corps gainé sous la table, tirage horizontal. Pieds surélevés pour durcir — c'est le levier de progression principal ici.",
  },
  {
    name: "Face pull bande",
    type: "musculation",
    zones: ["epaules", "trapezes"],
    priority: "primaire",
    equipment: ["bandes"],
    splitDays: ["pull", "push"],
    defaultSets: 4,
    defaultReps: "15-20",
    progression: ["bande", "reps", "tempo"],
    instructions: "Santé d'épaule + posture. Tirer vers le front, rotation externe en fin.",
  },
  {
    name: "Shrugs haltères",
    type: "musculation",
    zones: ["trapezes"],
    priority: "primaire",
    equipment: ["haltères"],
    splitDays: ["pull"],
    defaultSets: 4,
    defaultReps: "15-20",
    progression: ["charge", "reps", "tempo", "densite"],
    instructions:
      "Trapèzes visibles = silhouette Toji. Pause haute 2 s, pas de rotation d'épaule. À 10 kg, allonger la pause plutôt que les répétitions.",
  },
  {
    name: "Curl haltères",
    type: "musculation",
    zones: ["bras"],
    priority: "secondaire",
    equipment: ["haltères"],
    splitDays: ["pull"],
    defaultSets: 3,
    defaultReps: "12-15",
    progression: ["charge", "reps", "tempo"],
    instructions: "Volume accessoire, ne pas surpondérer.",
  },
  {
    name: "Curl marteau",
    type: "musculation",
    zones: ["avant-bras", "bras"],
    priority: "primaire",
    equipment: ["haltères"],
    splitDays: ["pull"],
    defaultSets: 3,
    defaultReps: "12-15",
    progression: ["charge", "reps", "tempo"],
    instructions: "Brachio-radial = épaisseur d'avant-bras.",
  },

  // ---------------- AVANT-BRAS / GRIP ----------------
  {
    name: "Dead hang barre",
    type: "musculation",
    zones: ["avant-bras", "dos"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["pull", "fullbody"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "45-60 s",
    progression: ["reps", "lest", "levier"],
    instructions:
      "Grip + décompression d'épaule. Objectif : 3×60 s puis passer en prise serviette.",
  },
  {
    name: "Dead hang serviette",
    type: "musculation",
    zones: ["avant-bras"],
    priority: "primaire",
    equipment: ["barre de tractions", "serviette"],
    splitDays: ["pull"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "20-40 s",
    progression: ["reps", "lest", "levier"],
    instructions: "Serviette sur la barre, prise épaisse. Brutal pour les mains.",
  },
  {
    name: "Handgrip séries longues",
    type: "musculation",
    zones: ["avant-bras"],
    priority: "primaire",
    equipment: ["handgrip"],
    splitDays: ["pull", "push", "legs"],
    defaultSets: 3,
    defaultReps: "max / main",
    progression: ["reps", "densite", "tempo"],
    instructions: "En fin de séance ou hors séance. Fermer complètement.",
  },
  {
    name: "Handgrip tenue isométrique",
    type: "musculation",
    zones: ["avant-bras"],
    priority: "primaire",
    equipment: ["handgrip"],
    splitDays: ["pull"],
    defaultSets: 3,
    defaultReps: "20-30 s / main",
    progression: ["reps", "densite"],
    instructions: "Fermé, tenir sans relâcher.",
  },
  {
    name: "Flexion/extension poignets haltères",
    type: "musculation",
    zones: ["avant-bras"],
    priority: "primaire",
    equipment: ["haltères", "chaise"],
    splitDays: ["pull", "push"],
    defaultSets: 3,
    defaultReps: "20 / sens",
    progression: ["charge", "reps", "tempo", "amplitude"],
    instructions: "Avant-bras posés sur les cuisses, amplitude complète.",
  },
  {
    name: "Wrist roller improvisé",
    type: "musculation",
    zones: ["avant-bras"],
    priority: "secondaire",
    equipment: ["haltères", "corde"],
    splitDays: ["pull"],
    defaultSets: 3,
    defaultReps: "3 allers-retours",
    progression: ["charge", "reps", "tempo"],
    instructions: "Enrouler/dérouler bras tendus devant soi.",
  },

  // ---------------- COU ----------------
  {
    name: "Neck harness / isométrie cou",
    type: "musculation",
    zones: ["cou"],
    priority: "primaire",
    equipment: ["bandes", "poids du corps"],
    splitDays: ["push", "pull"],
    defaultSets: 3,
    defaultReps: "20 s × 4 directions",
    progression: ["reps", "bande", "tempo"],
    instructions:
      "Résistance manuelle ou bande, 4 directions. Progression très lente, jamais de à-coup.",
  },
  {
    name: "Neck bridge (version douce)",
    type: "musculation",
    zones: ["cou"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "20 s",
    progression: ["reps", "amplitude"],
    instructions:
      "Sur le dos, appui tête + coussin. Amplitude minimale au début. À éviter si gêne cervicale.",
  },

  // ---------------- LEGS ----------------
  {
    name: "Squat bulgare",
    type: "musculation",
    zones: ["jambes", "fessiers"],
    priority: "secondaire",
    equipment: ["chaise", "haltères"],
    splitDays: ["legs"],
    defaultSets: 4,
    defaultReps: "10-15 / jambe",
    progression: ["charge", "reps", "tempo", "amplitude"],
    instructions: "Pied arrière sur la chaise, buste droit.",
  },
  {
    name: "Pistol squat (progression)",
    type: "musculation",
    zones: ["jambes"],
    priority: "secondaire",
    equipment: ["chaise", "poids du corps"],
    splitDays: ["legs"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "5-8 / jambe",
    progression: ["amplitude", "reps", "lest", "tempo"],
    instructions: "Descente vers la chaise d'abord, puis touche-lève, puis libre.",
  },
  {
    name: "Fentes marchées",
    type: "musculation",
    zones: ["jambes", "fessiers"],
    priority: "secondaire",
    equipment: ["haltères"],
    splitDays: ["legs", "fullbody"],
    defaultSets: 4,
    defaultReps: "12 / jambe",
    progression: ["charge", "reps", "densite"],
    instructions: "Genou frôle le sol, buste vertical.",
  },
  {
    name: "Soulevé de terre roumain haltères",
    type: "musculation",
    zones: ["jambes", "dos", "fessiers"],
    priority: "secondaire",
    equipment: ["haltères"],
    splitDays: ["legs"],
    defaultSets: 4,
    defaultReps: "12-15",
    progression: ["charge", "reps", "tempo", "unilateral"],
    instructions: "Charnière de hanche, dos neutre, étirement ischios.",
  },
  {
    name: "Hip thrust au sol",
    type: "musculation",
    zones: ["fessiers", "jambes"],
    priority: "secondaire",
    equipment: ["haltères", "chaise"],
    splitDays: ["legs"],
    defaultSets: 4,
    defaultReps: "15",
    progression: ["charge", "reps", "tempo", "unilateral"],
    instructions: "Dos sur la chaise, poussée par les talons, pause haute 2 s.",
  },
  {
    name: "Mollets debout unilatéral",
    type: "musculation",
    zones: ["mollets"],
    priority: "secondaire",
    equipment: ["haltères", "marche"],
    splitDays: ["legs"],
    defaultSets: 4,
    defaultReps: "20 / jambe",
    progression: ["charge", "reps", "tempo", "amplitude"],
    instructions: "Amplitude complète, pause basse.",
  },
  {
    name: "Squat sauté",
    type: "musculation",
    zones: ["jambes"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["legs", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "10 rapides",
    progression: ["reps", "densite", "lest"],
    instructions: "Explosivité — réception amortie. Qualité avant quantité.",
  },

  // ---------------- ABDOS / OBLIQUES ----------------
  {
    name: "Relevés de jambes suspendu",
    type: "musculation",
    zones: ["abdos"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["pull", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "10-15",
    progression: ["amplitude", "reps", "tempo", "lest"],
    instructions:
      "Jambes tendues si possible, sans balancier. Rétroversion en fin de mouvement.",
  },
  {
    name: "Toes to bar",
    type: "musculation",
    zones: ["abdos", "avant-bras"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["pull", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "6-10",
    progression: ["reps", "tempo", "lest"],
    instructions: "Version avancée des relevés de jambes.",
  },
  {
    name: "Windshield wipers suspendu",
    type: "musculation",
    zones: ["obliques", "abdos"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "8-12",
    progression: ["amplitude", "reps", "tempo"],
    instructions: "Jambes hautes, rotation contrôlée gauche/droite.",
  },
  {
    name: "Gainage planche",
    type: "musculation",
    zones: ["abdos"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["push", "fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "45-90 s",
    progression: ["reps", "levier", "lest"],
    instructions:
      "Bassin rétroversé, fessiers serrés. Au-delà de 90 s, durcir le levier plutôt qu'allonger.",
  },
  {
    name: "Gainage latéral",
    type: "musculation",
    zones: ["obliques"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["push", "fullbody"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "45 s / côté",
    progression: ["reps", "levier", "lest"],
    instructions: "Hanche haute, alignement épaule-cheville.",
  },
  {
    name: "Russian twist",
    type: "musculation",
    zones: ["obliques"],
    priority: "primaire",
    equipment: ["haltères"],
    splitDays: ["fullbody", "legs"],
    defaultSets: 4,
    defaultReps: "20 total",
    progression: ["charge", "reps", "tempo"],
    instructions: "Rotation depuis le tronc, pas les bras.",
  },
  {
    name: "Hollow body hold",
    type: "musculation",
    zones: ["abdos"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "30-45 s",
    progression: ["reps", "levier"],
    instructions: "Lombaires plaquées au sol. Bras tendus derrière la tête pour durcir.",
  },
  {
    name: "Ab wheel improvisé (serviette au sol)",
    type: "musculation",
    zones: ["abdos"],
    priority: "secondaire",
    equipment: ["serviette"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "8-12",
    progression: ["amplitude", "reps", "tempo"],
    instructions: "Glisser les mains vers l'avant, dos neutre. Amplitude progressive.",
  },

  // ---------------- FULL BODY / EXPLOSIVITÉ ----------------
  {
    name: "Burpees",
    type: "musculation",
    zones: ["jambes", "pecs", "abdos"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 5,
    defaultReps: "15",
    progression: ["reps", "densite"],
    instructions: "Conditionnement. Alternative : EMOM 10 min.",
  },
  {
    name: "Pompes pliométriques",
    type: "musculation",
    zones: ["pecs", "epaules"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 5,
    defaultReps: "6-8 explosives",
    progression: ["reps", "levier", "densite"],
    instructions: "Puissance de poussée — transfert direct sur la frappe.",
  },
  {
    name: "Tractions explosives",
    type: "musculation",
    zones: ["dos"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 5,
    defaultReps: "4-6",
    progression: ["reps", "lest", "densite"],
    instructions: "Monter le plus vite possible, descente contrôlée.",
  },
  {
    name: "Sprint sur place / high knees",
    type: "musculation",
    zones: ["jambes", "abdos"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 10,
    defaultReps: "30 s / 30 s",
    progression: ["reps", "densite"],
    instructions: "Cardio Ippo. Réduire la récupération avant d'allonger l'effort.",
  },
  {
    name: "Bear crawl",
    type: "musculation",
    zones: ["abdos", "epaules"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["fullbody"],
    bodyweight: true,
    defaultSets: 4,
    defaultReps: "30 s",
    progression: ["reps", "densite", "tempo"],
    instructions: "Genoux à 2 cm du sol, déplacement lent.",
  },
  {
    name: "Corde à sauter",
    type: "musculation",
    zones: ["mollets", "jambes"],
    priority: "secondaire",
    equipment: ["corde"],
    splitDays: ["fullbody", "muaythai"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "5 min",
    progression: ["reps", "densite"],
    instructions: "Base du footwork boxeur. Appuis légers sur l'avant du pied.",
  },

  // ---------------- MOBILITÉ ----------------
  {
    name: "Rotations d'épaules bâton (shoulder dislocates)",
    type: "mobilite",
    zones: ["epaules"],
    priority: "primaire",
    equipment: ["bandes", "bâton"],
    splitDays: ["mobilite", "repos", "push"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "10",
    progression: ["amplitude", "reps"],
    instructions:
      "Prise large, bras tendus, passer devant/derrière. Rétrécir la prise avec les semaines — c'est la mesure du progrès.",
  },
  {
    name: "Cat-cow + segmentation thoracique",
    type: "mobilite",
    zones: ["dos"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "repos"],
    bodyweight: true,
    defaultSets: 2,
    defaultReps: "10",
    progression: ["amplitude", "tempo"],
    instructions: "Vertèbre par vertèbre, respiration lente.",
  },
  {
    name: "Rotation thoracique quadrupédie (thread the needle)",
    type: "mobilite",
    zones: ["dos", "epaules"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "repos"],
    bodyweight: true,
    defaultSets: 2,
    defaultReps: "10 / côté",
    progression: ["amplitude", "reps"],
    instructions: "Main derrière la tête, ouvrir vers le plafond.",
  },
  {
    name: "90/90 hanches",
    type: "mobilite",
    zones: ["jambes"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "legs", "repos"],
    bodyweight: true,
    defaultSets: 2,
    defaultReps: "8",
    progression: ["amplitude", "reps", "tempo"],
    instructions:
      "Base de la mobilité de hanche pour les kicks. Passage lent d'un côté à l'autre, sans les mains quand c'est possible.",
  },
  {
    name: "Cossack squat",
    type: "mobilite",
    zones: ["jambes", "fessiers"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "legs"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "8 / côté",
    progression: ["amplitude", "reps", "lest"],
    instructions: "Adducteurs + amplitude de hanche. Talons au sol.",
  },
  {
    name: "Fente basse + rotation (world's greatest stretch)",
    type: "mobilite",
    zones: ["jambes", "dos"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "repos", "legs"],
    bodyweight: true,
    defaultSets: 2,
    defaultReps: "6 / côté",
    progression: ["amplitude", "reps"],
    instructions: "Échauffement complet en un mouvement.",
  },
  {
    name: "Étirement ischios actif (jambe tendue)",
    type: "mobilite",
    zones: ["jambes"],
    priority: "primaire",
    equipment: ["bandes"],
    splitDays: ["mobilite", "repos"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "5 cycles / jambe",
    progression: ["amplitude", "reps", "tempo"],
    instructions:
      "Bande au pied, monter la jambe tendue. PNF : contracter 5 s contre la bande, relâcher, gagner quelques centimètres, tenir.",
  },
  {
    name: "Grand écart facial — progression",
    type: "mobilite",
    zones: ["jambes"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "90-120 s",
    progression: ["amplitude", "reps"],
    instructions:
      "Descente jusqu'au seuil tolérable, respiration. Mesurer la distance sol-bassin et la reporter dans les repères de mobilité.",
  },
  {
    name: "Ouverture de cheville (dorsiflexion au mur)",
    type: "mobilite",
    zones: ["mollets", "jambes"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "legs"],
    bodyweight: true,
    defaultSets: 2,
    defaultReps: "10 / jambe",
    progression: ["amplitude", "reps"],
    instructions: "Genou vers le mur sans décoller le talon.",
  },
  {
    name: "Suspension passive à la barre",
    type: "mobilite",
    zones: ["epaules", "dos"],
    priority: "primaire",
    equipment: ["barre de tractions"],
    splitDays: ["mobilite", "repos", "pull"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "30-60 s",
    progression: ["reps", "amplitude"],
    instructions: "Relâchement complet, décompression.",
  },
  {
    name: "Étirement psoas / fléchisseurs de hanche",
    type: "mobilite",
    zones: ["jambes"],
    priority: "primaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "repos"],
    bodyweight: true,
    defaultSets: 3,
    defaultReps: "45 s / côté",
    progression: ["amplitude", "reps"],
    instructions: "Fente genou au sol, bassin en rétroversion, fessier serré.",
  },
  {
    name: "Mobilité cervicale contrôlée (CARs cou)",
    type: "mobilite",
    zones: ["cou"],
    priority: "secondaire",
    equipment: ["poids du corps"],
    splitDays: ["mobilite", "repos"],
    bodyweight: true,
    defaultSets: 2,
    defaultReps: "5 / sens",
    progression: ["amplitude", "reps"],
    instructions: "Cercles lents et contrôlés, amplitude sans douleur.",
  },
];
